services:
  mysql:
    image: mysql:8.0
    container_name: matchable_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: matchable_checkout
      MYSQL_USER: matchable_user
      MYSQL_PASSWORD: matchable_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - matchable_network

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matchable_php
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: matchable_checkout
      DB_USER: matchable_user
      DB_PASSWORD: matchable_password
    networks:
      - matchable_network

  nginx:
    image: nginx:alpine
    container_name: matchable_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/matchable-frontend:/usr/share/nginx/html
    depends_on:
      - php
    networks:
      - matchable_network

  redis:
    image: redis:alpine
    container_name: matchable_redis
    ports:
      - "6379:6379"
    networks:
      - matchable_network

volumes:
  mysql_data:

networks:
  matchable_network:
    driver: bridge